### PR TITLE
Improve error message when a tag is not found and match is set.

### PR DESCRIPTION
**Pull request by jenshnielsen**
If match is set and you do not have any tags matching this but you do have other tags the error shown is `git describe` could not find a tag` which is slightly confusing since there are tags and running git describe at the command line will return a tag. This just tweaks the error message to include the match argument in such a case.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
It was not obvious from a few mins of looking how to best update the test data depending on if match is used or not

**Comment by jwodder** [comment]
@jenshnielsen I've taken care of the tests, as well as various improvements to ensure that all mentions of `git describe` include not only `--match` but all other options passed as well.

**Comment by jenshnielsen** [comment]
Thanks @jwodder that looks like a great improvement and much more useful than my original contribution

**Comment by jwodder** [comment]
@jenshnielsen This has just been released in versioningit v3.1.0.

**Pull request merged**
